import React from 'react';
import {
  Cat,
  Dog,
  Flame,
  Coffee,
  ArrowUp,
  ArrowDown,
  Sparkles,
  Circle,
  ArrowLeft,
  AlignCenter,
  ArrowRight,
  Check,
  X,
  Smile,
  Ship,
  Table as TableIcon,
  Clock,
  Cake,
  Rabbit,
  Milk,
  Fish,
  User,
  Sun,
  Apple,
  TreePine,
  Palette,
  DoorOpen,
  Square,
  Gift,
  Waves,
  Crown,
  Home,
  Bird,
  ChefHat,
  Grape,
  Key,
  Leaf,
  Footprints,
  Hand,
  Gem,
  Bed,
  Lock,
  Monitor,
  Cookie,
  Wind,
  Flag,
  Bell,
  CircleDot,
  Mouse,
  CreditCard,
  Mic,
  Disc,
  Trash2,
  Car,
  Frown,
  Octagon,
  Music,
  HelpCircle
} from 'lucide-react';

const iconMap: Record<string, React.ComponentType<{ className?: string }>> = {
  // Required mapping items
  cat: Cat,
  dog: Dog,
  hot: Flame,
  pot: Coffee,
  up: ArrowUp,
  down: ArrowDown,

  // Position Pilot items
  beginning: ArrowLeft,
  middle: AlignCenter,
  end: ArrowRight,

  // Binary items
  yes: Check,
  no: X,

  // Other items from the game vocabulary
  balloon: Circle,
  ship: Ship,
  table: TableIcon,
  clock: Clock,
  cake: Cake,
  rabbit: Rabbit,
  milk: Milk,
  fish: Fish,
  doll: Smile,
  man: User,
  sun: Sun,
  apple: Apple,
  tree: TreePine,
  paint: Palette,
  fox: Dog,
  lion: Cat,
  door: DoorOpen,
  window: Square,
  gift: Gift,
  swim: Waves,
  hat: Crown,
  nest: Home,
  penguin: Bird,
  carrot: ChefHat,
  ball: Circle,
  grapes: Grape,
  key: Key,
  leaf: Leaf,
  stone: Circle,
  zebra: Square,
  sock: Footprints,
  glove: Hand,
  ring: Circle,
  cap: Crown,
  king: User,
  diamond: Gem,
  bucket: Circle,
  dolphin: Fish,
  finger: Hand,
  cot: Bed,
  lock: Lock,
  rock: Gem,
  desk: Monitor,
  feet: Footprints,
  chips: Cookie,
  fan: Wind,
  flag: Flag,
  bell: Bell,
  hand: Hand,
  button: CircleDot,
  glass: Coffee,
  nose: Smile,
  mouse: Mouse,
  card: CreditCard,
  wind: Wind,
  house: Home,
  bird: Bird,
  sing: Mic,
  fire: Flame,
  dish: Disc,
  bin: Trash2,
  tank: Circle,
  moth: Flame,
  blue: Palette,
  cab: Car,
  bread: Cookie,
  girl: User,
  cry: Frown,
  stop: Octagon,
  sad: Frown,
  dance: Music,
  mark: Check,
  green: Palette,
  cow: Smile,
};

export function getOptionIcon(text: string): React.ReactElement {
  const normalized = text.trim().toLowerCase();
  
  // If it's a number (for Position plates in Sound Trail)
  if (/^\d+$/.test(normalized)) {
    return <Sparkles className="w-6 h-6" />;
  }

  const IconComponent = iconMap[normalized] || Sparkles;
  return <IconComponent className="w-6 h-6" />;
}
