import React from 'react';
import {
  Cat,
  Dog,
  Flame,
  Coffee,
  ArrowUp,
  ArrowDown,
  Sparkles,
  Circle,
  ArrowLeft,
  AlignCenter,
  ArrowRight,
  Check,
  X,
  Smile,
  Ship,
  Table as TableIcon,
  Clock,
  Cake,
  Rabbit,
  Milk,
  Fish,
  User,
  Sun,
  Apple,
  TreePine,
  Palette,
  DoorOpen,
  Square,
  Gift,
  Waves,
  Crown,
  Home,
  Bird,
  ChefHat,
  Grape,
  Key,
  Leaf,
  Footprints,
  Hand,
  Gem,
  Bed,
  Lock,
  Monitor,
  Cookie,
  Wind,
  Flag,
  Bell,
  CircleDot,
  Mouse,
  CreditCard,
  Mic,
  Disc,
  Trash2,
  Car,
  Frown,
  Octagon,
  Music,
  Scissors,
  Swords,
  Ear,
  Eye,
  BookOpen,
  Heart,
  Calendar,
  Layers,
  Activity,
  ShoppingBag,
  Send,
  HelpCircle,
  Star,
  RotateCcw,
  Banana,
  Bath,
  Bean,
  Book,
  Bus,
  Candy,
  Cherry,
  Church,
  Drum,
  Edit,
  Egg,
  Film,
  Hop,
  Lamp,
  Mail,
  Map,
  Moon,
  Pill,
  Pizza,
  Plane,
  Play,
  Pocket,
  Route,
  School,
  Speech,
  Tent,
  Train,
  Wrench,
  Bug,
  Shield
} from 'lucide-react';

const iconMap: Record<string, React.ComponentType<{ className?: string }>> = {
  // Required mapping items
  cat: Cat,
  dog: Dog,
  hot: Flame,
  pot: Coffee,
  up: ArrowUp,
  down: ArrowDown,

  // Position Pilot items
  beginning: ArrowLeft,
  middle: AlignCenter,
  end: ArrowRight,

  // Binary items
  yes: Check,
  no: X,

  // Level 1:
  mat: Bed,
  fox: Dog,
  rib: Heart,
  bun: Cookie,
  cab: Car,
  mop: Trash2,
  sun: Sun,
  tin: Square,
  bat: Activity,
  hat: Crown,
  rat: Mouse,
  sat: TableIcon,
  pin: Flag,
  pen: Mic, // Fallback to Mic
  fin: Fish,
  cup: Coffee,
  tub: Bed,
  nut: CircleDot,
  log: TreePine,
  bed: Bed,
  red: Palette,

  // Level 2:
  brake: Octagon,
  market: ShoppingBag,
  push: ArrowUp,
  spoon: Coffee,
  spill: Waves,
  brush: Palette,
  drink: Coffee,
  mint: Leaf,
  power: Flame,
  large: ArrowUp,
  table: TableIcon,
  pillow: Bed,
  truck: Car,
  pink: Palette,
  dress: User,
  flower: Sparkles,
  grass: Leaf,
  clock: Clock,
  chair: TableIcon,
  mouse: Mouse,
  house: Home,
  bread: Cookie,
  shirt: User,
  sweet: Cake,
  fruit: Apple,

  // Level 3:
  blanket: Bed,
  temple: Home,
  drumstick: Music,
  children: User,
  mustard: Leaf,
  simple: Circle,
  reverse: RotateCcw,
  neighbour: User,
  immediate: Clock,
  position: ArrowLeft,
  wandering: Waves,
  rubbish: Trash2,
  yellow: Palette,
  factory: Home,
  arrow: ArrowRight,
  disturb: X,
  marbles: CircleDot,
  thunder: Flame,
  whisper: Mic,
  journey: Ship,
  forever: Clock,
  special: Star,
  silence: Mic,
  picture: Square,

  // Short/Long Vowels & Homophones:
  cut: Scissors,
  cute: Smile,
  bit: Cookie,
  bite: Cookie,
  sit: TableIcon,
  site: Home,
  mate: User,
  mall: ShoppingBag,
  male: User,
  fine: Smile,
  tile: Square,
  mope: Frown,
  cop: Lock,
  cope: Smile,
  tap: Waves,
  pine: TreePine,
  hate: Frown,
  tube: Circle,
  cape: Crown,
  kite: Wind,
  ripe: Apple,
  wine: Coffee,
  hope: Heart,
  note: Disc,
  cube: Square,
  fit: Activity,
  fight: Swords,
  wok: ChefHat,
  woke: Sun,
  rid: Trash2,
  ride: Activity,
  car: Car,
  care: Heart,
  rode: Activity,
  mad: Frown,
  made: ChefHat,
  bet: CreditCard,
  beet: Leaf,
  pile: Layers,
  mill: Wind,
  mile: Flag,
  reed: Leaf,
  feed: Cake,
  bake: ChefHat,
  rip: Scissors,
  men: User,
  mean: Frown,
  wit: Clock,
  white: Square,
  snack: Cookie,
  snake: Leaf,
  rack: TableIcon,
  rake: Leaf,
  lack: X,
  lake: Waves,
  pick: Key,
  pike: Fish,
  sin: Frown,
  sine: Waves,
  spit: Frown,
  spite: Frown,
  fill: Waves,
  file: Disc,
  smock: User,
  smoke: Wind,
  hid: Lock,
  hide: Lock,
  bait: Fish,
  son: User,
  hear: Ear,
  here: ArrowDown,
  bale: Square,
  bail: Lock,
  threw: ArrowRight,
  through: ArrowRight,
  bored: Frown,
  board: TableIcon,
  read: BookOpen,
  tale: BookOpen,
  bear: Cat,
  bare: Eye,
  hour: Clock,
  our: User,
  course: ArrowRight,
  coarse: Palette,
  heal: Heart,
  heel: Footprints,
  prey: Cat,
  pray: Crown,
  hare: Rabbit,
  hair: Smile,
  pair: Square,
  pear: Apple,
  knot: CircleDot,
  due: Calendar,
  dew: Waves,
  meat: Cookie,
  pale: Palette,
  pail: Trash2,
  rain: Waves,
  rein: Hand,
  tail: Cat,
  stair: Layers,
  stare: Eye,
  peace: Check,
  piece: Cake,
  steel: Gem,
  steal: Lock,
  which: Crown,
  witch: Crown,
  sent: Send,
  scent: Flame,
  weak: Frown,
  week: Calendar,
  wrote: BookOpen,
  rote: RotateCcw,
  right: ArrowRight,
  write: BookOpen,
  see: Eye,
  sea: Waves,
  weather: Wind,
  whether: HelpCircle,
  by: ShoppingBag,
  buy: ShoppingBag,
  vain: Smile,
  vein: Activity,
  hole: Circle,
  whole: Circle,

  // Standard items from original mappings
  balloon: Circle,
  ship: Ship,
  cake: Cake,
  rabbit: Rabbit,
  milk: Milk,
  fish: Fish,
  doll: Smile,
  man: User,
  apple: Apple,
  tree: TreePine,
  paint: Palette,
  lion: Cat,
  door: DoorOpen,
  window: Square,
  gift: Gift,
  swim: Waves,
  nest: Home,
  penguin: Bird,
  carrot: ChefHat,
  ball: Circle,
  grapes: Grape,
  key: Key,
  leaf: Leaf,
  stone: Circle,
  zebra: Square,
  sock: Footprints,
  glove: Hand,
  ring: Circle,
  cap: Crown,
  king: User,
  diamond: Gem,
  bucket: Circle,
  dolphin: Fish,
  finger: Hand,
  cot: Bed,
  lock: Lock,
  rock: Gem,
  desk: Monitor,
  feet: Footprints,
  chips: Cookie,
  fan: Wind,
  flag: Flag,
  bell: Bell,
  hand: Hand,
  button: CircleDot,
  glass: Coffee,
  nose: Smile,
  card: CreditCard,
  wind: Wind,
  bird: Bird,
  sing: Mic,
  fire: Flame,
  dish: Disc,
  bin: Trash2,
  tank: Circle,
  moth: Flame,
  blue: Palette,
  girl: User,
  cry: Frown,
  stop: Octagon,
  sad: Frown,
  dance: Music,
  mark: Check,
  green: Palette,
  cow: Smile,

  // Semantic mappings for newly discovered level words
  about: HelpCircle,
  achieve: Sparkles,
  actor: User,
  address: Mail,
  admit: Check,
  afternoon: Sun,
  again: RotateCcw,
  aid: Heart,
  aim: Star,
  air: Wind,
  allow: Check,
  ambit: Circle,
  amid: AlignCenter,
  angel: Sparkles,
  ankle: Footprints,
  ant: Bug,
  antler: Crown,
  apron: ChefHat,
  arch: Home,
  area: Square,
  arm: Hand,
  arrive: ArrowRight,
  ash: Flame,
  ask: HelpCircle,
  ate: Cookie,
  back: ArrowLeft,
  bag: ShoppingBag,
  banana: Banana,
  band: Music,
  bank: CreditCard,
  bark: TreePine,
  basket: ShoppingBag,
  bath: Bath,
  batter: Cake,
  battle: Swords,
  beach: Waves,
  bean: Bean,
  beat: Activity,
  bee: Bug,
  beetroot: Leaf,
  behind: ArrowRight,
  belt: Shield,
  bench: TableIcon,
  bend: RotateCcw,
  best: Star,
  bill: CreditCard,
  birth: Cake,
  black: Palette,
  blank: Square,
  bleach: Waves,
  blew: Wind,
  blink: Eye,
  blood: Heart,
  boat: Ship,
  book: Book,
  bottle: Coffee,
  bug: Bug,
  bus: Bus,
  bush: TreePine,
  cafe: Coffee,
  camel: Cat,
  candy: Candy,
  cattle: Cat,
  cheese: Cookie,
  cherry: Cherry,
  church: Church,
  coconut: Apple,
  coffee: Coffee,
  corn: Leaf,
  crayon: Palette,
  crib: Bed,
  deer: Cat,
  drum: Drum,
  edit: Edit,
  egg: Egg,
  elbow: Activity,
  elephant: Cat,
  emu: Bird,
  engine: Activity,
  fig: Apple,
  film: Film,
  flash: Flame,
  fly: Bird,
  frog: Cat,
  gate: DoorOpen,
  helmet: Shield,
  hero: User,
  hippo: Cat,
  hop: Hop,
  horse: Cat,
  hut: Home,
  ink: Palette,
  jacket: User,
  jam: Cookie,
  kettle: Coffee,
  kid: User,
  kitchen: Home,
  lamb: Cat,
  lamp: Lamp,
  leg: Footprints,
  lemon: Apple,
  life: Heart,
  mail: Mail,
  mango: Apple,
  map: Map,
  meal: Cake,
  melon: Apple,
  mirror: Square,
  monkey: Cat,
  moon: Moon,
  mother: User,
  mouth: Smile,
  mug: Coffee,
  neem: Leaf,
  net: Layers,
  octopus: Fish,
  palm: Hand,
  pan: ChefHat,
  pant: User,
  park: TreePine,
  pet: Dog,
  pickle: Cookie,
  pill: Pill,
  pizza: Pizza,
  plane: Plane,
  plant: Leaf,
  play: Play,
  plum: Apple,
  pocket: Pocket,
  pony: Cat,
  pool: Waves,
  potato: Apple,
  queen: Crown,
  road: ArrowRight,
  rope: Activity,
  rose: Sparkles,
  route: Route,
  sack: ShoppingBag,
  school: School,
  seal: Fish,
  seat: TableIcon,
  sheep: Cat,
  shoe: Footprints,
  shop: ShoppingBag,
  shower: Waves,
  silk: Layers,
  sky: Sun,
  sleep: Bed,
  soap: Waves,
  song: Music,
  spanner: Wrench,
  spear: Swords,
  speech: Speech,
  street: ArrowRight,
  tape: Activity,
  teeth: Smile,
  tent: Tent,
  tomato: Apple,
  train: Train,
  uncle: User,
  wall: Square,
  washing: Waves,
  wasp: Bug,
  watches: Clock,
  water: Waves,
  wrench: Wrench,
  yoga: User,
};

export function getOptionIconComponent(text: string): React.ComponentType<{ className?: string }> {
  const normalized = text.trim().toLowerCase();
  return iconMap[normalized] || Sparkles;
}

export function getOptionIcon(text: string): React.ReactNode {
  const normalized = text.trim().toLowerCase();
  
  if (normalized === 'yes' || normalized === 'no') {
    return null;
  }
  
  // If it's a number (for Position plates in Sound Trail)
  if (/^\d+$/.test(normalized)) {
    return <Sparkles className="w-6 h-6" />;
  }

  const IconComponent = iconMap[normalized] || Sparkles;
  return <IconComponent className="w-6 h-6" />;
}
